### ISSUE TITLE
Changing GDM background does not appear to work

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [sakithb/wallhub#3]
Distro: Fedora 39
Gnomer version: 45

**Comment by sakithb** [comment]
Were there any errors when setting the background or did it say it was successful?

**Comment by IdkWhatToCallMe123** [comment]
Video showing what I did:
[螢幕錄影 2024-01-22 21-20-50.webm](https://github.com/sakithb/wallhub/assets/74187631/57ac8c32-be0b-43ca-b93e-3d940581c268)
Result:
![PXL_20240122_200810520](https://github.com/sakithb/wallhub/assets/74187631/a532968b-2016-485e-a39a-c6775db27355)

Short answer: I got no indication that that nothing was wrong, but nothing really explicitly telling me that it was success, I just assumed to bc the reset button became enabled.

**Comment by sakithb** [comment]
It should show a password prompt and then a notification saying it was successful. Can you run `pkexec echo "Successful"` in your terminal and let me know if it showed you a prompt to enter a password.

**Comment by IdkWhatToCallMe123** [comment]
> It should show a password prompt and then a notification saying it was successful. Can you run `pkexec echo "Successful"` in your terminal and let me know if it showed you a prompt to enter a password.

yea this works fine

**Comment by sakithb** [comment]
Can you post the journal while you set the background. This can help me identify errors.

**Comment by IdkWhatToCallMe123** [comment]
Sorry but where can I find the journal?

**Comment by sakithb** [comment]
Run `journalctl -f` in the terminal and apply the background. After applying, press `ctrl+c` in the terminal to stop printing the journal and paste the output here. Try to apply the background as quickly as possible or the journal might get too big to paste here.

**Comment by IdkWhatToCallMe123** [comment]
Here are the logs:
                                
[1月 24 13 22 57 PURGED.txt](https://github.com/sakithb/wallhub/files/14038164/1.24.13.22.57.PURGED.txt)

**Comment by sakithb** [comment]
`[Wallhub] Error: GLib.SpawnError: 無法執行副程序「glib-compile-resources」(沒有此一檔案或目錄)` Can you translate the non-english words for me?

**Comment by IdkWhatToCallMe123** [comment]
Oops sorry didn't think about that sorry xd
`[Wallhub] Error: GLib.SpawnError: Failed to execute child process “glib-compile-resources” (No such file or directory)
`

**Comment by sakithb** [comment]
Do you have `glib2-devel` installed on your system?

**Comment by IdkWhatToCallMe123** [comment]
Oh okay after installing that everything works now!

**Comment by sakithb** [comment]
Thats great! Probably should include it as a dependency in the description.
